name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install The Graph CLI
        run: yarn global add @graphprotocol/graph-cli
      - name: Add The Graph access token
        run: graph auth --node https://api.thegraph.com/deploy ${{ secrets.SECRET_TOKEN }}
      - name: Install modules
        run: yarn install
      - name: Install modules
        run: yarn prepare-xdai
      - name: Generate dist
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Deploy
        run: graph deploy --node https://api.thegraph.com/deploy/ --ipfs https://api.thegraph.com/ipfs/ adamazad/aqua-xdai
