# This workflow run integration tests
name: Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MNEMONIC: ${{ secrets.GANACHE_MNEMONIC }}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Build Docker containers
        run: docker-compose up -d
      - name: Build subgraph manifest
        run: yarn prepare-rinkeby
      - name: Generate graph typings
        run: yarn codegen
      - name: Run tests
        run: yarn test
